name       : dukto
version    : 6.0
release    : 4
source     :
    - https://stroblindustries.com/solus-tarballs/dukto-6.0.tar.xz : f0c390db228fe942ccbca04c0296304e3097aeda2c8984923d5634afaf8ba481
license    : GPL-2.0-or-later
component  : network.util
summary    : A simple, fast and multi-platform file transfer tool for LAN users
description: |
    A simple, fast and multi-platform file transfer tool for LAN users.
builddeps  :
    - pkgconfig(QtCore)
setup      : |
    %qmake4
build      : |
    %make
install    : |
    install -Dm00755 dukto $installdir/usr/bin/dukto
    install -Dm00644 dukto.desktop $installdir/usr/share/applications/dukto.desktop
    install -Dm00644 dukto.png $installdir/usr/share/pixmaps/dukto.png
